#desarrollo
spring.datasource.url=jdbc:oracle:thin:@10.0.100.157:20200:siga02
spring.datasource.username=SISVENVI
spring.datasource.password=SISVENVI21

#produccion
#spring.datasource.url=jdbc:oracle:thin:@10.5.115.15:1522:desa
#spring.datasource.username=sisvenvi
#spring.datasource.password=sisvenvi20

spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.connectionProperties=useUnicode=true;characterEncoding=utf-8;

spring.thymeleaf.encoding=UTF-8
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
server.port=8888

#LOCAL
#spring.datasource.jndi-name=java:jboss/datasources/ventanillaDS
#desarrollo
#spring.datasource.jndi-name=java:/ventanillaDS
#produccion
#spring.datasource.jndi-name=java:jboss/datasources/BootWarDeployment

spring.mail.host=ofine.mef.gob.pe
spring.mail.port=25
spring.mail.username=ventanilla@mef.gob.pe
spring.mail.password=ir%Wd,m3f
#spring.mail.username=stramite@mef.gob.pe
#spring.mail.password=c0rt3s1a
spring.mail.properties.mail.protocol=smtp
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.smtp.auth.ntlm.domain=mef.gob.pe

#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp-mail.outlook.com

spring.servlet.multipart.max-file-size=3500MB
spring.servlet.multipart.max-request-size=3500MB
 
server.servlet.session.cookie.http-only = false
server.servlet.session.cookie.secure = false  
server.servlet.session.cookie.max-age = 300m
 
server.connection-timeout=600000
#spring.mvc.async.request-timeout=600000
spring.transaction.default-timeout=600000
file.upload=uploads

file.fileserver=/UPLOAD/
#file.fileserver=/UPLOAD

#sisvenvi
database.package = SISVENVI.PCK_LGJ_MANTENIMIENTO
database.pck_mef_consulta = SISVENVI.PCK_VEN_MEF_CONSULTA
database.pck_mef_mantenimiento = SISVENVI.PCK_VEN_MEF_MANTENIMIENTO
database.seg_pck_consulta = SISVENVI.PCK_VEN_CONSULTA
database.pck_ven_mantenimiento = SISVENVI.PCK_VEN_MANTENIMIENTO

database.seg_pck_usuario = SISVENVI.PCK_SEG_USUARIO
database.seg_pck_login = SISVENVI.PCK_SEG_LOGIN
database.pck_seg_consulta = SISVENVI.PCK_SEG_CONSULTA
database.pck_seg_persona = SISVENVI.PCK_SEG_PERSONA
database.seg_pck_mef_perfil = SISVENVI.PCK_SEG_PERFIL
database.pck_seg_menu = SISVENVI.PCK_SEG_MENU
database.pck_ven_enlace_encuesta = SISVENVI.PCK_VEN_ENLACE_ENCUESTA

database.idsistema=2
database.micorreo=L

captcha.time = 900
                                       
## JWT Properties
grokonez.app.jwtSecret=n2r5u8xADGKaPdSgVkYp3s6v9yBEHMbQeThWmZq4t7wzCFJNcRfuW3Op09q
grokonez.app.jwtExpiration=86400

#reCaptcha
google.recaptcha.key.site=6Lc2HMQZAAAAAOdNlIWk1ODRHIVI0s0GvGf_TZAF
#6LcivqQZAAAAAJVOLzipzQvpO4AqJ8msw7n_7Lk7
google.recaptcha.key.secret=6Lc2HMQZAAAAALQ8dsrQ6WAOgOAwl9xPFDYM024N
#6LcivqQZAAAAAHMpOUwINAClNYjgXjSM43KFpCov

#app.url =http://localhost:8888/logo-mef 
#DESARROLLO
#app.url =http://10.5.115.4:8090/ventanilla/logo-mef
#PRODUCCION
app.url =https://www.mef.gob.pe/ventanilla/logo-mef

document.months_per_report = 3


server.servlet.context-path=/ventanilla

project.version=1.0.5-SNAPSHOT